### ISSUE TITLE
The cursor of normal mode disappeared after upgrade to atom 1.24.0-beta0

### ISSUE THREAD

**Issue by yubaoquan** [t9md/atom-vim-mode-plus#1001] opened 2017-12-13 09:35 UTC
As the title said. No error message in console.

# Check list

You have to check all before open issue.

- [x] Try with latest Atom and latest vim-mode-plus.
- [x] Pick descriptive and non-ambiguous subject
- [x] Express "what" you want(feature? config option?, behavior change?) in short sentence(not long!).
- [x] Contrast current behavior if you want to change current behavior, with sample text, operation(keystroke) and result.
- [x] Include real use case so that maintainer can understand "why" you need help.
- [x] Include Atom(`atom --version`), vim-mode-plus version, and OS version(e.g. macOS Sierra 10.12.3).
- [x] If keybinding issue, Read https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#some-keybinding-not-working

**Comment by hultberg** [comment] 2017-12-13 09:54
Duplicate of #998

**Closed** 2017-12-13 10:20 UTC
