### ISSUE TITLE
Redo should always leave cursor at beginning of change.

### ISSUE THREAD

**Issue by jordwalke** [t9md/atom-vim-mode-plus#14] opened 2015-10-07 07:36 UTC
See corresponding issue here: https://github.com/atom/vim-mode/issues/342

Undo/redo is critical to matching the feel of Vim.

Specifically, open a document, press insert `i`, and start typing a very long paragraph. Make sure you press several newlines as well. Then hit `escape`. Undo the change and redo it - take note of where your cursor is left when undoing/redoing.

Another nuance: try the same thing, but instead of pressing `i` to begin inserting, try pressing `o` to "open" a line. You'll notice that redo leaves your cursor position where the cursor was at the time you pressed `o`.

Thank you.

**Comment by t9md** [comment] 2015-11-30 04:27
@jordwalke 
Do you know to manually download and run atom in dev-mode?
I want you to check the behavior and give feedback to me.
The implementation was very simple and easy unlike I expected.
I'm not sure I can understand problem correctly, want your evaluation and feedback.

```
cd ~/github
git clone https://github.com/t9md/atom-vim-mode-plus.git
cd atom-vim-mode-plus

# create symlink to ~/.atom/dev/packages/vim-mode-plus which will be active on dev-mode
apm link -d

# launch in dev-mode
atom -d
```

when you finished evaluation
```
cd ~/github/atom-vim-mode-plus
# remove symlink
apm unlink -d
```

**Comment by jordwalke** [comment] 2015-11-30 06:39
Awesome, I've been trying out bleeding edge `atom-vim-mode-plus`, just so I can help catch bugs in `master`, but I didn't know about dev mode. That makes it much easier, thanks.

**Comment by t9md** [comment] 2015-12-02 14:46
Released as v0.7.0.
My approach is to track changes as marker, this is a little heavy but simple(no need to manual range intersecting calculation).

Although I don't think this is complete and reach equivalent level of pure Vim.

I want to stop to tackle this issue for now.

**Comment by jordwalke** [comment] 2015-12-02 21:29
I cloned and tried in dev mode, but it seems the cursor is not placed at the beginning of "redone" changes. How can I confirm I am in dev mode?

**Comment by jordwalke** [comment] 2015-12-02 21:30
To reproduce the problem:

Open new file. Enter lines of text with many newlines. Undo "u" and then redo "ctrl+r". The cursor was left at the end of the text, not the beginning.

**Comment by t9md** [comment] 2015-12-02 23:50
Since I already published to atom.io, you can just try in normal installation.
BTW to make sure your in dev-mode, check red rectangle icon on statusbar only shown in dev-mode.

To try this feature, enable
`setCursorToStartOfChangeOnUndoRedo`
To try flashing changed area
`flashOnUndoRedo`

**Comment by jordwalke** [comment] 2015-12-03 00:02
Okay, so I think the final thing needed to make this feel like Vim, is to put the cursor at the start of the change that was *just undone* when you `undo`. The reason why Vim works like this is so you can always to `undo`, `redo`, `undo`, `redo` and watch the change replayed over and over without your cursor moving. I'm assuming that this wouldn't be too difficult now that you have the markers in place.

**Comment by t9md** [comment] 2015-12-03 00:11
Are you saying after you tried?
Please put procedure to describe your expectation by contrasting Current VS Preffered.
Since I think I put cursor on start of change when `undo`, your report is not match my understanding.

So give me specific(procedure in operation level(like `iXXXX<Esc>u<Ctrl-r>`) when you describe some behavior SHOULD XXX.
BTW, I'm glad your feedback in this issue and other issue that teach me a lot about feature.

**Comment by jordwalke** [comment] 2015-12-03 03:14
Yes, I actually tried.
I just realized that it actually does do the right thing on undo *except* when the change that you are making significantly changes the size (I'm guessing the markers are no longer valid). I'll get you a reproducible sequence of key strokes.

**Comment by jordwalke** [comment] 2015-12-03 03:19
Start with this text in your buffer. `a z`, and start with the cursor right before the `a`.

1. Hit `sb<Esc>u<ctrl-r>u<ctrl-r>`

You've replaced `a` with `b` and then undo/redo several times doesn't disturb the cursor position.

But now, let's replace a with much more text so you disrupt the length of the line from which you recorded the markers.

2. Hit `sbbbbbbbbbbbbb<Esc>u<ctrl-r>u<ctrl-r>`

Notice that the cursor moves to the incorrect place on undo, but the corect place on redo. It *should* behave like the first example where you only replaced `a` with one `b` instead of several.

**Comment by t9md** [comment] 2015-12-03 03:25
@jordwalke Thanks, very clear. And I also noticed this behavior just before reading your comment above.
When I paste multiple line by `p`, cursor position is as expected in undo/redo.
But when I type exactly same text in insert mode then exit cursor position is wrong in undo.

**Comment by jordwalke** [comment] 2015-12-03 07:09
You are so close. No one has ever taken their Vim editor this far.

**Comment by t9md** [comment] 2015-12-04 07:06
Released as v0.7.1.
I think I could reach comfortable level. But I know its not 100% accurate but cover most of case.
And I like flash range for removed(red) and added(green) range.

Thanks for inviting me to tackle this topic!

I want close this issue :smile:

**Comment by t9md** [comment] 2015-12-04 07:15
here the gif

![undo-redo](https://raw.githubusercontent.com/t9md/t9md/19e4086ce7f16bd802fd8ec609b422a45a05f8db/img/vim-mode-plus/flash-undo-redo.gif)

**Comment by t9md** [comment] 2015-12-08 07:47
@jordwalke I'm waiting for your feedback for v0.7.1.
How was that, did you tries?

**Comment by bronson** [comment] 2015-12-10 08:01
It looks like @jordwalke's examples don't quite work...  The cursor should remain on `a` the whole time you're undoing and redoing.  `u` works, but `ctrl-r` puts the cursor _after_ the change.

![bug3](https://cloud.githubusercontent.com/assets/1776/11710026/0fe99876-9ed1-11e5-9c72-55cbf35dfaac.gif)


I'm on 0.8.0.

**Comment by t9md** [comment] 2015-12-10 08:06
You set?
> To try this feature, enable
setCursorToStartOfChangeOnUndoRedo
To try flashing changed area
flashOnUndoRedo

**Comment by bronson** [comment] 2015-12-10 08:12
Oh gotcha.  I can't read.  Yeah, now it works.

Why isn't that on by default?  :)

**Comment by t9md** [comment] 2015-12-10 08:19
Just want to evaluation period for a while.
And also need spec.

**Comment by t9md** [comment] 2015-12-10 08:19
By the way I like flashing feature very much how is you?

**Comment by bronson** [comment] 2015-12-10 08:40
Turns out I like Atom's default ctrl-z and ctrl-shift-z quite a bit...  Undo leaves the undone text selected, and that's a pretty sweet highlight.  If `u` and `ctrl-r` matched this behavior, I'd be pretty happy.

Current v-m-p behavior is a little too noisy for my taste... maybe if the highlight colors were muted a little, and maybe faded in and out softer?

Also, unless I'm misunderstanding, it seems to miss the first line?  And it only works for lines or bigger changes, not for words?  (which makes sense, if the highlight is skipping the first line)

![bug3](https://cloud.githubusercontent.com/assets/1776/11710728/232b280a-9ed6-11e5-8521-f2245b7f6768.gif)

**Comment by t9md** [comment] 2015-12-10 08:55
I intentionally clear selection after undo to avoid sequential u lowercase selected char. I want to keep atom's original behavior as much as I can, to do that I have to remember last command is vim-mode-plus:undo then differentiate u behavior in this particular case.

For color noisiness I'll check later.

For omitting first line, this is maybe because of code I did skip first line to conform vim's behavior on `p` linewise text. Ill also check lator.
But note, i already doing dirty work under the hood for this feature, i don't think I could reach 100% comfortable level.

**Comment by t9md** [comment] 2015-12-10 14:01
For color, I changed color softer.

For this part
> Also, unless I'm misunderstanding, it seems to miss the first line? And it only works for lines or bigger changes, not for words? (which makes sense, if the highlight is skipping the first line)

See following GIF, its work for word. And don't skip first line. Just ignore my above comment, I checked code and trying to reproduce issue but couldn't.

https://github.com/t9md/atom-vim-mode-plus/wiki/GIFs#flash-on-undo-and-redo

What precise operation of your case(buffer content, line ending, other package disabled, keystroke).
I want to reproduce it in my environment.

Thanks.

**Comment by jordwalke** [comment] 2015-12-11 07:56
I did try and it mostly worked but I found some issues. I didn't report them because it sounded like you didn't want to work on this anymore.

btw: I totally agree that undo/redo should *never* leave highlighted selections. The results are devastating if you press "u" while selection is highlighted. Your redo stack is destroyed.

**Comment by t9md** [comment] 2015-12-11 09:47
If you notice any issue for this feature, its worth to know it for me since I know its not complete solution.
By keeping unresolved issue on mind, I might be able to find better solution in future(sometime with help of Atom core API improvement).

For `u` I think I can solve as I note by differentiating normal visual `u` and special `u` just after undo.
But need some time to experiment evaluate its good or bad..

**Comment by jordwalke** [comment] 2015-12-13 02:31
I noticed that in 0.8, when you use `o` for "open on new line below", the undo/redo cursor point should be marked at the point where the cursor was when you hit `o`, but right now it is marked at the *end* of that line that you pressed `o` on.

Example, in new file:
1. Open a file with the text: `a b <|> c d e` where your cursor is the `<|>` is. Hit escape. Your normal mode cursor will be covering up the `b`.
2. Hit `o`, then enter the text `x y z` followed by `escape` again.

You should be in normal mode, and the final file should look like:
```
a b c d e
x y z
```
If you `undo`/`redo` you will see that the cursor moves incorrectly between `e` and `x`, when `undo`/`redo` should leave the cursor on the `b` while pressing `undo/redo`.

**Comment by jordwalke** [comment] 2015-12-13 02:35
There is a similar issue for `A`, which means to insert after the final character on the current line. Only, for `A`, vim itself is a little inconsistent and the undo/redo point is on the final character of the line you were on when you pressed `A`. Regardless of where you chose to make the cursor mark, right now in 0.8, this plugin will jump between *two* separate cursor locations when executing undo/redo. It should seldom be the case that `undo/redo` jump character position when doing `undo` followed by `redo` (except when it would be impossible otherwise). The reason, is that it allows you to "replay" any change you do without disrupting cursor position.

**Comment by t9md** [comment] 2015-12-13 03:39
Fot the second `A` issue I did some improvement. Here is the example

* Initial condition
mode = normal, cursor = at `a` char
```
a b c d
```

* operation
`AZZZ\nZZZ<Esc>`

* final-text
cursor = is on last `Z` on 2nd line
```
a b c dZZZ
ZZZ
```

* operation
`undo` revert text to `a b c d` with cursor on `d`.
`redo` revert text to `a b c dZZZ\nZZZ` with cursor on **first instance of `Z`** on **1st** line.
This behavior is same as pure Vim.
In v0.8.0 cursor was put on **first column of 2ndline** on `undo`.

**Comment by t9md** [comment] 2015-12-13 03:50
For the `o` issue you reported.
I couldn't find good solution at least current my knowledge.

To solve this issue, I need deeper understanding in Atom's marker restoration and might need some upstream API improvement.
(BTW: Atom's native undo(`cmd-z`) properly put cursor on position where `o` pressed, but redo put cursor on end of change).

The big motivation to put cursor on start of change is to avoid user lost in buffer like `where am I editing?`. In this purpose current behavior achieved minimum purpose and consistent at least vim-mode-plus package.

**Closed** 2016-01-11 14:06 UTC
Labels: atom-is-not-vim, compatiblity, enhancement, priority-high
