### ISSUE TITLE
Cursor Jump to other place while typing in insert mode

### ISSUE THREAD

**Issue by geohuz** [t9md/atom-vim-mode-plus#875] opened 2017-09-14 05:39 UTC
# Check list

- Atom version: 1.19.5
- vim-mode-plus version: 1.4
- macOS Sierra 10.12.6)
-  vim-mode disabled
- Tried to latest stable atom version with latest vim-mode-plus: yes

This issue happens randomly and is very annoying. The case is, sometimes when switching to the insert mode, and I start typing and  found that the cursor was in another location, so the character  was inserted in wrong place. And it's happened several weeks before, I kept upgrading the vim-mode-plus and it doesn't fix the issue.

**Comment by t9md** [comment] 2017-09-14 07:37
Can you share your config.cson?

**Comment by geohuz** [comment] 2017-09-14 08:05
Here you go:

```
"*":
  "atom-beautify":
    general:
      _analyticsUserId: "903f0caa-0d03-429d-b8d3-ac2b7d126afb"
  "atom-package-deps":
    ignored: []
  core:
    automaticallyUpdate: false
    customFileTypes:
      "source.ini": [
        ".buckconfig"
        ".flowconfig"
        ".hgrc"
      ]
      "source.json": [
        "BUCK.autodeps"
      ]
      "source.python": [
        "BUCK"
      ]
    disabledPackages: [
      "language-javascript"
      "nuclide"
      "language-clojure"
    ]
    telemetryConsent: "limited"
    themes: [
      "atom-light-ui"
      "atom-light-syntax"
    ]
  editor: {}
  "exception-reporting":
    userId: "6e4942bd-feb9-443b-8fcc-bd638d15d59d"
  "flow-ide": {}
  "linter-ui-default":
    panelHeight: 81
  "lisp-paredit":
    enabled: false
    strict: false
  nuclide:
    "nuclide-flow":
      warnOnNotInstalled: false
    "nuclide-home":
      showHome: false
  "vim-mode-plus":
    charactersToAddSpaceOnSurround: [
      "("
      "{"
      "["
      "<"
    ]
    keymapCCToChangeInnerSmartWord: true
    keymapPToPutWithAutoIndent: true
    setCursorToStartOfChangeOnUndoRedoStrategy: "simple"
  welcome:
    showOnStartup: false
```

**Comment by t9md** [comment] 2017-09-14 08:22
Thanks, I couldn't get hint for why this issue happenning.
Can you say this issue is started from recent Atom update?

Also from recent atom-update, the issue  "cursor displayed at wrong place" was reported.
https://github.com/t9md/atom-vim-mode-plus/issues/855

Your issur is similar to #855?

**Comment by geohuz** [comment] 2017-09-14 11:43
I could confirm this issue started from Atom update, I couldn't remember the version number when updated, It was a 'major' update I think.

**Comment by t9md** [comment] 2017-09-15 06:40
OK you are now not alone, me experienced it.
But what I want/need to know is to find a way to reproduce 100%.
So that I can dig the cause and fix it.
Currently I cannot imagine what situation, condition cause this issue.
Will keep an eye on it.

**Comment by mingelz** [comment] 2017-09-15 09:45
I have the same issue in several days, i think it's not similar to #855 , and the issue can not reappear stably :(

**Comment by t9md** [comment] 2017-09-15 10:07
OK, I understand how frustrating it is, since I've experienced that issue, so no longer collecting "me too" report.

l still need report for **hint or complete reproduction steps**.

**Comment by xinghanggogogo** [comment] 2017-09-28 08:45
I ran into this problem after updating MAC OS and atom, and now I think the issue come from the updating of Max OS or atom and its not a vim-mode-plus's bug.
because after i got the same frustriting jump,  i tried to use another atom's plugins, the atom/vim-mode(0.66.0) and your vim-mode-visual-block(0.2.16), and the jump occured as the same.
i miss the perfect vim mode in atom badly, and hope that  my steps can help you.

**Comment by t9md** [comment] 2017-10-01 01:18
@kiiiit Thanks, I'm not sure the issue you reported here is same issue other people reported.
Anyway I could reproduce with the steps you explained, thanks. Will try to investigate.

**Comment by t9md** [comment] 2017-10-01 01:27
I couldn't get meaning of following explanation.
But now, after trying out with actual text, I'm clearly understand.

> still,
> The problem is not only the position of the cursor,
> Even if editing such as deletion of the source of another place is added after the procedure of ①,
> That editing content also returns.
>
> As a behavior, rather than changing the cursor position,
> It is said that I said that I will return to the point when I did the procedure of ①.

If I delete some text at the end of step-1, deleted text is **reverted** at first-char-input-timing of step-3.
Really critical issue.

**Comment by t9md** [comment] 2017-10-01 01:32
People who created or commented are seem to be either of Chinese or Japanese, so this issue have same shared condition.
Which condition is  "IME switching in normal-mode auto visual-charactewise-mode".

**Comment by t9md** [comment] 2017-10-01 01:52
- Issue happens with both Google IME and MacOS bundled Kotoeri.
- Issue still happens after I disabled "auto-shift visual-mode" code logic.
- So this might be upstream(atom-core) issue.
- After I could find minimum reproduction steps, will report to atom-core.
  - I want to reproduce without vmp and with safe-mode to make sure vmp and other pkg is irrelevant. related.

**Comment by t9md** [comment] 2017-10-01 03:45
Could reproduce **without vim-mode**.

v.1.18: No issue
v.1.19, v1.20, v1.21-beta: reproduce-able.

So this bug started from v1.19([editor rendering overhaul](http://blog.atom.io/2017/06/22/a-new-approach-to-text-rendering.html))

**Comment by t9md** [comment] 2017-10-01 04:53
Thanks @kiiiit again, I could not track down issue and report to atom-core without your reproduction steps.
I now believe originally reported issue is also cause by IME pops up on normal-mode.
Will wait upstream atom-core issue progress.

**Comment by t9md** [comment] 2017-10-13 01:01
Today atom-v1.21.1 and atom-1.22.0-beta1 are released.
I confirmed this critical issue FIXED on both versions :tada:.

**Closed by t9md** 2017-10-13 01:01 UTC
Labels: bug, upstream-issue

**Comment by mingelz** [comment] 2017-10-13 07:09
Thanks a lot! Cheers~ 👍

**Comment by babywolfvn** [comment] 2018-09-26 02:45
@t9md I was using Atom 1.30.0 and still get this same issue. After reading this thread I tried 1.21.1 and got it fixed. Can you fix this for latest version?

**Comment by t9md** [comment] 2018-09-26 15:05
If you can reproduce it with the latest version of Atom, then please open the new issue with necessary information as long as providing steps to reproduce.

Thanks.

**Comment by t9md** [comment] 2018-10-07 03:14
I want to know the link to that discussion, please.

**Comment by babywolfvn** [comment] 2018-10-08 07:07
@t9md Here you go:

https://discuss.atom.io/t/cursor-jump-when-typing-in-vietnamese-input-method-macos/59276

Thanks @t9md .

**Comment by georgebrindeiro** [comment] 2018-11-09 04:11
I'm having the same issue on Atom 1.30.0 running on a Mac

I don't use atom-vim-mode-plus, so it's probably Atom Core or something else

**Comment by georgebrindeiro** [comment] 2018-11-09 04:16
Might be related: https://github.com/atom/atom/pull/17985

**Comment by Davtyanag** [comment] 2019-03-03 11:25
The same happens to me
