### ISSUE TITLE
Error when operating on inside or around

### ISSUE THREAD

**Issue by kimroen** [t9md/atom-vim-mode-plus#835] opened 2017-08-18 14:58 UTC
### Steps to reproduce

1. Open a file
2. Enter insert mode
3. Write `Hi I'm a "quoted string" from space`
4. Enter normal mode
5. Navigate in between the quotes
6. Try to change the contents of the quoted string using `c-i-"`
7. Observe error below

The same thing happens with similar operations like delete inside parentheses or around quotes.

**Atom**: 1.19.2 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package 0.97.2

### Stack Trace

Uncaught TypeError: _.partition is not a function

```
At /Users/kimroen/.atom/packages/vim-mode-plus/lib/operation-stack.js:162

TypeError: _.partition is not a function
    at getCharacterRangeInformation (/packages/vim-mode-plus/lib/pair-finder.js:13:27)
    at QuoteFinder.find (/packages/vim-mode-plus/lib/pair-finder.js:202:39)
    at _Class.Pair.getPairInfo (/packages/vim-mode-plus/lib/text-object.coffee:211:29)
    at _Class.Pair.getRange (/packages/vim-mode-plus/lib/text-object.coffee:220:17)
    at _Class.TextObject.selectTextObject (/packages/vim-mode-plus/lib/text-object.coffee:118:17)
    at /packages/vim-mode-plus/lib/text-object.coffee:86:13
    at _Class.Base.countTimes (/packages/vim-mode-plus/lib/base.coffee:130:7)
    at _Class.TextObject.select (/packages/vim-mode-plus/lib/text-object.coffee:82:6)
    at _Class.TextObject.execute (/packages/vim-mode-plus/lib/text-object.coffee:74:8)
    at Change.Operator.selectTarget (/packages/vim-mode-plus/lib/operator.coffee:254:13)
    at Change.ActivateInsertMode.execute (/packages/vim-mode-plus/lib/operator-insert.coffee:108:8)
    at OperationStack.execute (/packages/vim-mode-plus/lib/operation-stack.js:208:33)
    at OperationStack.process (/packages/vim-mode-plus/lib/operation-stack.js:190:12)
    at OperationStack.run (/packages/vim-mode-plus/lib/operation-stack.js:113:14)
    at /packages/vim-mode-plus/lib/base.coffee:380:35)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:13.4.0 application:new-file (input.hidden-input)
     -0:12.8.0 vim-mode-plus:insert-after-end-of-line (input.hidden-input)
     -0:07.7.0 intentions:highlight (input.hidden-input)
  2x -0:07.6.0 editor:move-to-beginning-of-word (input.hidden-input)
  2x -0:07.2.0 core:move-left (input.hidden-input)
     -0:06.4.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -0:05.9.0 vim-mode-plus:change (input.hidden-input)
     -0:05.7.0 vim-mode-plus:inner-double-quote (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-beautify 0.30.5 
atom-css-unit-converter 1.1.1 
atom-ctags 5.1.0 
atom-elixir 0.2.3 
atom-handlebars 1.3.0 
atom-jinja2 0.6.0 
atom-liquid-snippets 0.3.0 
atom-pair 2.0.12 
atom-typescript 11.0.7 
autocomplete-ctags 0.4.1 
autocomplete-elixir 1.5.15 
autocomplete-emojis 2.5.0 
autocomplete-paths 2.8.0 
base16-ocean-dark 1.2.0 
base16-ocean-dark-spacegray 0.13.0 
better-handlebars 0.1.1 
block-travel 1.0.5 
busy-signal 1.4.3 
color-picker 2.2.5 
contrast-syntax 0.8.1 
contrast-ui 0.53.0 
ctags-status 1.3.7 
cucumber 0.6.0 
cucumber-step 0.2.0 
dash 1.7.1 
docblockr 0.11.0 
editorconfig 2.2.2 
ember-snippets 2.1.0 
emmet 2.4.3 
ex-mode 0.17.0 
file-icons 2.1.11 
flogger 0.3.5 
font-viewer 0.3.1 
goto-definition 1.3.4 
Handlebars 1.8.0 
highlight-selected 0.13.1 
intentions 1.1.5 
language-babel 2.71.0 
language-docker 1.1.8 
language-elixir 0.19.0 
language-haml 0.25.1 
language-handlebars 0.2.0 
language-ini 1.19.0 
language-liquid 0.6.0 
language-matlab 0.2.1 
language-rspec 0.6.3 
language-rust 0.4.12 
language-stylus 0.2.0 
last-cursor-position 0.9.2 
line-ending-converter 1.3.2 
linter 2.2.0 
linter-coffeelint 1.3.1 
linter-eslint 8.2.1 
linter-haml 2.0.1 
linter-jscs 4.1.2 
linter-jshint 3.1.5 
linter-rubocop 2.1.1 
linter-rust 0.8.0 
linter-ui-default 1.6.7 
local-history 4.3.0 
markdown-preview-enhanced 0.14.8 
minimap 4.29.6 
minimap-autohide 0.10.1 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.2 
minimap-pigments 0.2.2 
minimap-split-diff 0.3.7 
monokai 0.24.0 
pigments 0.40.2 
platformio-ide-terminal 2.5.5 
project-manager 3.3.5 
qolor 0.4.2 
rails-i18n 0.1.3 
rails-i18n-autocomplete 0.4.0 
rails-rspec 0.3.2 
rails-transporter 1.7.1 
ror-refactor 0.3.1 
rspec 0.4.0 
ruby-block-converter 4.0.1 
ruby-test 1.0.2 
seti-monokai 0.3.1 
seti-ui 1.9.0 
sort-lines 0.14.0 
split-diff 1.5.0 
tab-title 0.3.5 
vertical-tabs 1.0.5 
vim-mode-plus 0.97.2 
vim-mode-plus-keymaps-for-surround 0.2.1 
```

**Comment by t9md** [comment] 2017-08-19 00:52
Hi, I tried with your repro step, but couldn't reproduce it.
This is strange issue I cannot understand why it can happen.

https://github.com/t9md/atom-vim-mode-plus/blob/eeb88cfc9b0aedb2c7d07363fd2023c75c18bc18/lib/pair-finder.js#L10-L16

What stacktrace saying is. `_.partition` is not function.
But not complain about `_.escapeRegExp` at first line of this function.
`_` is `required` at top of this file, why `_.partition` can be `undefined`?

Are you able to reproduce always with the repro step you explained?

**Comment by kimroen** [comment] 2017-08-19 21:02
Yes, it does always happen this way. It started happening after updating to Atom 1.19.

Thankfully - I've found the culprit!

After going through the process of disabling all my packages and enabling them one by one, I have determined that having `vim-mode-plus` and [`font-viewer`](https://github.com/ericfreese/font-viewer) enabled at the same time causes this issue.

Both of these depend on `underscore-plus`, so I'm assuming there's some kind of clobbering going on there. Maybe `font-viewer` has an older version that doesn't have `partition`, and you're getting that older version? Maybe it would get resolved by rebuilding Atom's `node_modules`?

I'm not sure what, if anything, could be done about this. I've disabled `font-viewer` so I can use Atom properly again.

What do you think?

**Comment by t9md** [comment] 2017-08-20 12:16
Each package's node_modules should be independent.
Enabling one package affecting to other package's behavior is very strange situation.

I'm not sure it actually affected by font-viewer package,
I need to investigate vmp's dependency semver declaration.

Can you give me exact same CLI command output as following command?

first one is underscore.js version, 2nd = underscore-plus version
then, grep to check `partition`, since font-viewer limit underscore-plus to 1.0.x, installed version is 1.0.6, and depending underscore.js have no `partition` definition.
But vmp's underscore have `_.partition`.
It should be same in your environment.

```
~%
~% cat ~/.atom/packages/font-viewer/node_modules/underscore{,-plus}/package.json| grep '"version":'
  "version": "1.5.2"
  "version": "1.0.6"
~% cat ~/.atom/packages/vim-mode-plus/node_modules/underscore{,-plus}/package.json| grep '"version":'
  "version": "1.6.0"
  "version": "1.6.6"
~% grep partition ~/.atom/packages/font-viewer/node_modules/underscore/underscore.js
[1] ~% grep partition ~/.atom/packages/vim-mode-plus/node_modules/underscore/underscore.js
  _.partition = function(array, predicate) {
~%
```

**Comment by kimroen** [comment] 2017-08-21 09:32
Here!

```
$ cat ~/.atom/packages/font-viewer/node_modules/underscore{,-plus}/package.json| grep '"version":'
cat: ~/.atom/packages/font-viewer/node_modules/underscore/package.json: No such file or directory
  "version": "1.0.6",

$ cat ~/.atom/packages/vim-mode-plus/node_modules/underscore{,-plus}/package.json| grep '"version":'
  "version": "1.6.0"
  "version": "1.6.6"

$ grep partition ~/.atom/packages/font-viewer/node_modules/underscore/underscore.js
grep: ~/.atom/packages/font-viewer/node_modules/underscore/underscore.js: No such file or directory
```

It certainly looks like this shines some light on the problem - my local font-viewer doesn't have `underscore`.

Some more tidbits (I don't know if these are helpful, but here they are anyway):

1. You need to reboot atom between enabling and disabling for the bug to show up or go away. This indicates it is related to startup or initialization in general
2. I always open atom using the `atom` cli command

**Comment by t9md** [comment] 2017-08-21 10:33
Humm, font-viewer not having undersore installed is just simple problem, it failed to install dependencies specified in it's `package.json`, so maybe it's cause is failing install process or something, anyway I don't have interests for that, fixing should be easy and should be done at user-side(I believe so), re-install font-viewer.

But I still have great interest why this wired install-state happen to affect vim-mode-plus's behavior.
This should not happen, if you can constantly reproduce issue, this is super important issue should be reported to Atom-core.

What is happening is vmp require-ing font-viewer's old undesrore-plus which have no depending underscore.js installed?

**Comment by t9md** [comment] 2017-08-21 10:35
Btw your CLI output **lacks** output of grepping "partiton" for vmp's underscore.

**Comment by kimroen** [comment] 2017-08-21 10:39
> Btw your CLI output lacks output of grepping "partiton" for vmp's underscore.

No, it's saying that `underscore.js` doesn't exists:

```
$ grep partition ~/.atom/packages/font-viewer/node_modules/underscore/underscore.js
grep: ~/.atom/packages/font-viewer/node_modules/underscore/underscore.js: No such file or directory
```

Did I misunderstand?

> Humm, font-viewer not having undersore installed is just simple problem, it failed to install dependencies specified in it's package.json, so maybe it's cause is failing install process or something, anyway I don't have interests for that, fixing should be easy and should be done at user-side(I believe so), re-install font-viewer.

Fair enough!

> But I still have great interest why this wired install-state happen to affect vim-mode-plus's behavior.
> This should not happen, if you can constantly reproduce issue, this is super important issue should be reported to Atom-core.

Yeah, it's weird. I can - every time I enable font-viewer and restart atom, this error happens. What exactly do you suggest I report to Atom core?

> What is happening is vmp require-ing font-viewer's old undesrore-plus which have no depending underscore.js installed?

That's what it seems like.

**Comment by t9md** [comment] 2017-08-21 10:44
> Btw your CLI output lacks output of grepping "partiton" for vmp's underscore.
> No, it's saying that underscore.js doesn't exists:

I wanted to know following command output
`grep partition ~/.atom/packages/vim-mode-plus/node_modules/underscore/underscore.js`

**Comment by kimroen** [comment] 2017-08-21 10:45
Oh, sorry! I keep thinking "vmp" is short for the font-viewer package for some reason.

It's there, though:

```
$ grep partition ~/.atom/packages/vim-mode-plus/node_modules/underscore/underscore.js
  _.partition = function(array, predicate) {
```

**Comment by kimroen** [comment] 2017-08-21 10:52
```
find ./ -type f | grep underscore
.//underscore-plus/lib/underscore-plus.js
.//underscore-plus/LICENSE.md
.//underscore-plus/node_modules/underscore/LICENSE
.//underscore-plus/node_modules/underscore/package.json
.//underscore-plus/node_modules/underscore/README.md
.//underscore-plus/node_modules/underscore/underscore-min.js
.//underscore-plus/node_modules/underscore/underscore.js
.//underscore-plus/package.json
.//underscore-plus/README.md
```

Aha, the non-flat way of installing dependencies from before npm 3, I think?

**Comment by t9md** [comment] 2017-08-21 10:55
ya, so OK, no problem.
Affecting other package is still issue.

How about this? next.
Can you compare require.cache with when-issue-happen and when-issue-not-happen by following steps.

1. Launch atom
2. Open chrome dev console, paste.
```javascript
Object.keys(require.cache).filter(p => p.search(/vim-mode-plus/) > 0).join("\n")
```

3. This is require cache which store required filepath, focus `underscore`'s path it really using.


<img width="1012" alt="atom-vim-mode-plus-117721-25015-yohw87_7o967jh5mi_md_ __var_folders_f0_r8q_rcqd1g1104ktb8kjzn7w0000gn_t_error_when_operating_on_inside_or_around_ _issue__835_ _t9md" src="https://user-images.githubusercontent.com/155205/29516234-8e34600e-86aa-11e7-9067-ed422bf57936.png">

**Comment by kimroen** [comment] 2017-08-21 11:00
When it's not happening:

```
"/Users/kimroen/.atom/packages/vim-mode-plus/lib/main.js
/Users/kimroen/.atom/packages/vim-mode-plus/lib/base.coffee
/Users/kimroen/.atom/packages/vim-mode-plus/node_modules/delegato/lib/delegator.js
/Users/kimroen/.atom/packages/vim-mode-plus/node_modules/mixto/lib/mixin.js
/Users/kimroen/.atom/packages/vim-mode-plus/lib/settings.js
/Users/kimroen/.atom/packages/vim-mode-plus/lib/global-state.js
/Users/kimroen/.atom/packages/vim-mode-plus/lib/vim-state.js
/Users/kimroen/.atom/packages/vim-mode-plus/lib/mode-manager.js
/Users/kimroen/.atom/packages/vim-mode-plus/lib/command-table.coffee
/Users/kimroen/.atom/packages/vim-mode-plus/lib/status-bar-manager.js
/Users/kimroen/.atom/packages/vim-mode-plus/lib/selection-wrapper.js
/Users/kimroen/.atom/packages/vim-mode-plus/lib/utils.js
/Users/kimroen/.atom/packages/vim-mode-plus/node_modules/underscore-plus/lib/underscore-plus.js
/Users/kimroen/.atom/packages/vim-mode-plus/node_modules/underscore/underscore.js
/Users/kimroen/.atom/packages/vim-mode-plus/lib/blockwise-selection.js
/Users/kimroen/.atom/packages/vim-mode-plus/lib/operation-stack.js
/Users/kimroen/.atom/packages/vim-mode-plus/lib/motion.coffee
/Users/kimroen/.atom/packages/vim-mode-plus/lib/cursor-style-manager.js
/Users/kimroen/.atom/packages/vim-mode-plus/lib/mark-manager.js
/Users/kimroen/.atom/packages/vim-mode-plus/lib/operator-insert.coffee
/Users/kimroen/.atom/packages/vim-mode-plus/lib/operator.coffee
/Users/kimroen/.atom/packages/vim-mode-plus/lib/mutation-manager.js
/Users/kimroen/.atom/packages/vim-mode-plus/lib/occurrence-manager.js
/Users/kimroen/.atom/packages/vim-mode-plus/lib/persistent-selection-manager.js
/Users/kimroen/.atom/packages/vim-mode-plus/lib/text-object.coffee
/Users/kimroen/.atom/packages/vim-mode-plus/lib/pair-finder.js
/Users/kimroen/.atom/packages/vim-mode-plus/lib/register-manager.js
/Users/kimroen/.atom/packages/vim-mode-plus/lib/input.js
/Users/kimroen/.atom/packages/vim-mode-plus/lib/misc-command.coffee
/Users/kimroen/.atom/packages/vim-mode-plus/lib/flash-manager.js"
```

*enable font-viewer, restart atom*

When issue is happening:

```
"/Users/kimroen/.atom/packages/vim-mode-plus/lib/main.js
/Users/kimroen/.atom/packages/vim-mode-plus/lib/base.coffee
/Users/kimroen/.atom/packages/vim-mode-plus/node_modules/delegato/lib/delegator.js
/Users/kimroen/.atom/packages/vim-mode-plus/node_modules/mixto/lib/mixin.js
/Users/kimroen/.atom/packages/vim-mode-plus/lib/settings.js
/Users/kimroen/.atom/packages/vim-mode-plus/lib/global-state.js
/Users/kimroen/.atom/packages/vim-mode-plus/lib/vim-state.js
/Users/kimroen/.atom/packages/vim-mode-plus/lib/mode-manager.js
/Users/kimroen/.atom/packages/vim-mode-plus/lib/command-table.coffee
/Users/kimroen/.atom/packages/vim-mode-plus/lib/status-bar-manager.js
/Users/kimroen/.atom/packages/vim-mode-plus/lib/selection-wrapper.js
/Users/kimroen/.atom/packages/vim-mode-plus/lib/utils.js
/Users/kimroen/.atom/packages/vim-mode-plus/lib/blockwise-selection.js
/Users/kimroen/.atom/packages/vim-mode-plus/lib/operation-stack.js
/Users/kimroen/.atom/packages/vim-mode-plus/lib/operator-insert.coffee
/Users/kimroen/.atom/packages/vim-mode-plus/lib/operator.coffee
/Users/kimroen/.atom/packages/vim-mode-plus/lib/mutation-manager.js
/Users/kimroen/.atom/packages/vim-mode-plus/lib/occurrence-manager.js
/Users/kimroen/.atom/packages/vim-mode-plus/lib/persistent-selection-manager.js
/Users/kimroen/.atom/packages/vim-mode-plus/lib/text-object.coffee
/Users/kimroen/.atom/packages/vim-mode-plus/lib/pair-finder.js
/Users/kimroen/.atom/packages/vim-mode-plus/lib/errors.js
/Users/kimroen/.atom/packages/vim-mode-plus/lib/motion.coffee
/Users/kimroen/.atom/packages/vim-mode-plus/lib/cursor-style-manager.js
/Users/kimroen/.atom/packages/vim-mode-plus/lib/mark-manager.js"
```

**Comment by t9md** [comment] 2017-08-21 11:06
WOW!! when issue happening, no underscore-plus entry under vim-mode-plus, its maybe required from font-viewer's node_module????

Really interesting issue, but I have no enough background to explain situation like this...
Want to really really know the reason!!

How about these two cmd(checking symbolik linked file)?.
```
find ~/.atom/packages/vim-mode-plus -type l
find ~/.atom/packages/font-viewer -type l
```

**Comment by t9md** [comment] 2017-08-21 11:17
To verify vim-mode-plus's resolved filePath for `underscore-plus`, can you do this?

1. vim ~/.atom/packages/vim-mode-plus/lib/utils.js
2. Insert `console.log("resolved path", require.resolve("underscore-plus"))` at very first line.
3. Start atom with/without font-viewer, and see console.log output from chromve-dev-console.

**Comment by kimroen** [comment] 2017-08-21 11:22
```
$ find ~/.atom/packages/vim-mode-plus -type l
/Users/kimroen/.atom/packages/vim-mode-plus/node_modules/.bin/cake
/Users/kimroen/.atom/packages/vim-mode-plus/node_modules/.bin/coffee
/Users/kimroen/.atom/packages/vim-mode-plus/node_modules/.bin/csonc
/Users/kimroen/.atom/packages/vim-mode-plus/node_modules/.bin/mkdirp
/Users/kimroen/.atom/packages/vim-mode-plus/node_modules/.bin/rimraf
/Users/kimroen/.atom/packages/vim-mode-plus/node_modules/.bin/semver

$ find ~/.atom/packages/font-viewer -type l
/Users/kimroen/.atom/packages/font-viewer/node_modules/fs-plus/node_modules/.bin/rimraf
```

This doesn't seem related?
The resolved paths:

1. Without font-viewer:
`resolved path /Users/kimroen/.atom/packages/vim-mode-plus/node_modules/underscore-plus/lib/underscore-plus.js`

2. With font-viewer:
`resolved path /Users/kimroen/.atom/packages/font-viewer/node_modules/underscore-plus/lib/underscore-plus.js`

Maybe worth noting: The first one logged when I clicked around in a file with the mouse, but the second one didn't log until I edited the file.

**Comment by t9md** [comment] 2017-08-21 11:37
> With font-viewer:
> resolved path /Users/kimroen/.atom/packages/font-viewer/node_modules/underscore-plus/lib/underscore-plus.js

Ya, we verified our hypothesis  finally. vmp resolving font-viewer's underscore-plus.
I don't have long experience node-js, can you explain why?
The lib search path used in require is modified in somewhere (by font-viewer???).
I'm not familiar  with library search path of node's require.

Btw, at this point I don't think this is vmp's issue, if this is frequently happen vmp would have be reported similar issue, but this is first one.

**Comment by t9md** [comment] 2017-08-21 11:55
I think this line is garbage, can you solve issue by comment out and issue can back by comment-in again?

Change source directly at line 13.
```
$ vim ~/.atom/packages/font-viewer/lib/font-viewer-view.coffee +13
```

https://github.com/ericfreese/font-viewer/blob/a978e7dc604474664ba5f1ed95e5d9aeaeeaad59/lib/font-viewer-view.coffee#L13

**Comment by kimroen** [comment] 2017-08-21 12:40
I agree that that doesn't look right, but after removing it the error still happens.

**Comment by kimroen** [comment] 2017-08-21 13:31
>Thanks.
>For now I will stop digging into further.

Totally okay! Hopefully having this issue here helps someone else :)

> You can fix it by re-installing it right?

No, reinstalling font-viewer doesn't make a difference unfortunately. I'm disabling the package to get around the issue.

I like my vim range operations more than I like previewing font files in atom ;)

**Comment by t9md** [comment] 2017-08-21 17:21
hummm, super strange issue.
Although I close this issue, I want to get update if you finally track down root cause.

**Closed by t9md** 2017-08-21 17:21 UTC
Labels: require repro-steps
