### ISSUE TITLE
Add command to go to start and end of screen line

### ISSUE THREAD

**Issue by LandonSchropp** [t9md/atom-vim-mode-plus#724] opened 2017-04-01 22:29 UTC
Atom version: 1.15.0
vim-mode-plus-version: 0.85.1
OS: MacOS Sierra 10.12.4

First of all, thanks for creating this great package! I'm in the process of migrating my configuration from Vim, and I like to navigate up and down based on visual lines. To achieve this in Vim, I set up my keybindings like this:

``` viml
nnoremap <silent> k gk
nnoremap <silent> j gj
```

I was able to achieve the same thing with `vim-mode-plus` by adding the following to my `keymap.cson` file (which is awesome!):

``` cson
'atom-text-editor.vim-mode-plus:not(.insert-mode)':
  'k': 'vim-mode-plus:move-up-screen'
  'j': 'vim-mode-plus:move-down-screen'
```

However, I was unable to bring over a few of my other bindings.

```
nnoremap <silent> 0 g0
nnoremap <silent> ^ g^
nnoremap <silent> $ g$
```

It doesn't seem like there are `vim-mode-plus` commands for these keybindings. If it's not too much trouble, it would be great if you could add the following commands:

* `move-to-beginning-of-line-screen`
* `move-to-first-character-of-line-screen`
* `move-to-last-character-of-line-screen`

**Comment by t9md** [comment] 2017-04-02 00:48
duplicate of #443.

**Closed** 2017-08-24 08:28 UTC
Labels: duplicate
