### ISSUE TITLE
Undo is not working properly jsx syntax is selected

### ISSUE THREAD

**Issue by neliojrr** [t9md/atom-vim-mode-plus#778] opened 2017-05-08 10:07 UTC
Issue: When I type undo it always left a code snippet without undo. Usually is a ending tag(e.g. `</div>`.

How to reproduce:
- Edit a .js file
- Set the syntax to JSX
- Write down some html code
- Type undo
- Does not work properly

GIF: 
![atom_issue](https://cloud.githubusercontent.com/assets/384017/25799793/c4656e5a-33e6-11e7-9afe-c4d8e2add61a.gif)

It's a bit specific. When I'm editing html files it doesn't happen. But maybe it's happening with some other file types.

- Atom version 1.16.0
- vim-mode-plus version: 0.91.0
- Your OS: macOS Sierra 10.12.4
- You disabled vim-mode? Yes

**Comment by t9md** [comment] 2017-05-08 12:28
- What the language-plugin for JavaScript (JSX). There are several packages.
- Do you need some snippet expansion to reproduce issue?
- Issue is 100% reproducable?
- When you could reproduce issue, can you correctly undo the change by normal `core:undo` (`cmd-z`) ?

**Comment by t9md** [comment] 2017-05-08 12:42
OK I think I could repro.
- Install `react` package.
- `Grammar Selector: Show`, then select `JavaScript( JSX )`.
- type `i<div>` then `escape`. At this point, text is `<div></div>` Since when I type `>`, closing tag is auto inserted.
- `u` to undo. now tex is
  - `</div>`, It should be empty. `u` should revert to the text state BEFORE entering `insert-mode`.

 
My impression for this issue is maybe React plugin do something special, I'll investigate but not sure fixable by vmp-side.

**Comment by t9md** [comment] 2017-05-08 13:00
Hi, found the cause.

This line of atom-react package.

```coffeescript
editor.insertText('</' + tagName + '>', {undo: 'skip'})
```

https://github.com/orktes/atom-react/blame/master/lib/atom-react.coffee#L247

Inserting text with the options `{undo: 'skip'}`, means, "skip this insertion when undoing, in other word don't maintain buffer change history for this time mutation".
I can't understand why they explicitly setting this option.
I disabled in locally and confirmed the `u`(`undo`) works as expected.
If some mutation skips undo history, nothing I can do by my vmp side. I'll open issue on `ato-react`, but I'm not atom-react user.
If you need, pls add follow-up commment on that issue.

**Comment by t9md** [comment] 2017-05-08 13:35
sent PR.
Nothing I can do after all.

**Comment by neliojrr** [comment] 2017-05-08 18:13
Thank you! I really appreciate that! I'll follow the issue that you opened on atom. 👍

**Closed** 2017-05-25 08:56 UTC
