### ISSUE TITLE
Question about marking `m` command and gutter.

### ISSUE THREAD

**Issue by jordwalke** [t9md/atom-vim-mode-plus#378] opened 2016-09-18 07:15 UTC
I have the gutter disabled (hidden/toggled off), so line numbers aren't shown.
When I use vmp's `m x` to mark a named `x` location, the gutter shows itself as soon as I hit `m`, and then hides itself again after I hit `x`. Is this a known issue? Is it a desired feature? If so, is it (or should it be) configurable?

**Comment by t9md** [comment] 2016-09-18 07:30
I tried, but was no issue.

1. I can hide gutter by `editor:toggle-line-numbers`
2. `m x`
3. move cursor then ``` ` x ``` to  jump to marked position.

On 2-3, gutter is remain hidden.

So I want to  know enabling only  just vmp solve problem or not.

**Comment by jordwalke** [comment] 2016-09-18 08:21
Ah, it must be another plugin (such as the "gutter" plugin I have installed - for toggling the gutter).

**Comment by jordwalke** [comment] 2016-11-13 07:10
This is the plugin I use which causes the problem. I think it's the only way to hide the gutter, right? (Not just the line numbers, but the whole gutter).
https://atom.io/packages/toggle-gutter

Also, I notice that when hitting `m`, comments in my code momentarily become italicized (when they otherwise aren't). Is that related? It seems very strange.

**Comment by t9md** [comment] 2016-11-13 08:37
Thanks for asking, I noticed the rude behavior of vmp by your issue.

# 1st, for your issue

You can hide line-number by `editor:toggle-line-numbers` command.
I keymap it to `space t n`(`t` is prefix for toggle in my local rule).

So you don't need toggle-gutter package(I tried and check code and saw nothing special feature that package provides).

You might also notice you want padding when hide line-number.
In that case use following css in your `style.less`.

```less
atom-text-editor {
  .scroll-view {
    padding-left: 0.5em;
  }
}
```

# 2nd The rudeness of vmp.

Currently when vim-mode-plus read input from user, it read user input via keymap, not via un-shown text-form(It was in older version).
This is a dirty effort to [improve slow performance of f, F, t, T, m](https://github.com/t9md/atom-vim-mode-plus/pull/448).
To read user-input via keymap, it temporarily swap CSS class of editorElement, I believe this cause break style which add special CSS class into editorElement.

I have to be more unobtrusive, will treat different issue.

I want to remove current dirty hack for read-user-input-via-keymap if I found better approach, but original implementation to read user-input-from-mini-editor was too slow.

**Comment by jordwalke** [comment] 2016-11-15 01:28
I confirmed that this was the reason for the italics style becoming temporarily messed up while hitting `m` as well. It's the removal of the `.editor` class. Should plugins/styles just not target the `.editor` class? It seems they should be able to reliably

**Comment by jordwalke** [comment] 2016-11-15 01:30
I can easily fix it for my own custom css hacks on `.editor`, and maybe we can just fix the issue in the hide-gutter plugin if that's easier (and results in faster vmp performance).

**Comment by jordwalke** [comment] 2016-11-15 01:32
Actually, I just found it's harder for me to do even in my custom css hacks in my `.less` stylesheet.

```
// disable italic comments and source code in any syntax theme
atom-text-editor::shadow {
  .comment, .source * {
      font-style: normal !important;
  }
}
```

It seems this leaves me no choice but to target the `.editor` style?

**Comment by t9md** [comment] 2016-11-15 02:13
Which should be fixed is rude behavior of vim-mode-plus.

I'll try to provide quick fix.

For the question where to style is, if style is for text-editor, `atom-text-editor` tag is natural target I think.

**Comment by t9md** [comment] 2016-11-15 02:13
But `.editor` should be fine.
I should fix vmp that's is the root cause.

**Comment by t9md** [comment] 2016-11-15 02:25
You are using atom-beta?

**Comment by t9md** [comment] 2016-11-15 02:32
If you are using atom 1.13.0-beta, you should remove `::shadow` part from your style.
ShadowDom is completely removed from 1.13(So maintaining both 1.12 and 1.13 is now difficult at this time for me).

For fixing rudeness of vmp, I can provide fix without sacrificing performance improvement for `m`.
Just want to know you are using beta.

**Comment by jordwalke** [comment] 2016-11-15 02:43
Yes, I'm using beta. I had no idea shadow DOM was removed. Good to know.

I thought they moved *towards* shadow DOM, now they move away?

**Comment by t9md** [comment] 2016-11-15 02:46
Move away, it's big change, so all syntax theme use different css class since it's no longer protected by shadow boundary.
If you update the which is provided for beta, which is not correctly colored in current stable.
Since current stable require `::shadow`, theme for beta don't have `::shadow`.

**Comment by t9md** [comment] 2016-11-15 15:49
Next vmp release no longer remove outer-vmp-css-class, so editor class won't be removed.

**Closed by t9md** 2016-11-15 15:49 UTC
Labels: Q&A
