### ISSUE TITLE
Cursor position wrong after switch IME and type.

### ISSUE THREAD

**Issue by yubaoquan** [t9md/atom-vim-mode-plus#840] opened 2017-08-22 06:52 UTC
# Check list

- Atom version info(`atom --version`)
Atom    : 1.19.2
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

- vim-mode-plus version.
0.98.0

- Your OS(e.g. macOS Sierra 10.12.3)
macOS Sierra 10.12.6

- You disabled vim-mode? You cannot use both vim-mode and vim-mode-plus simultaneously.
Not installed vim-mode

- Tried to latest stable atom version with latest vim-mode-plus.
Yes

- Keybinding issue? [Read this](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#some-keybinding-not-working).
No

- If you follow [Ideal issue reporting](https://github.com/t9md/atom-vim-mode-plus/wiki/IssueReport#ideal-issue-reporting), it's great!

Steps to reproduce:
1. Create a file a.html.
2. Input this content: `<div></div>`.
3. Press esc to switch to normal mode.
4. Move cursor to the middle of the div tag.
![1](https://user-images.githubusercontent.com/2340296/29552302-43b5a8a4-8749-11e7-92fa-2aa0f3714b9c.jpg)

5. Change IME to local language (This usually happens when I focus back from other app).
![2](https://user-images.githubusercontent.com/2340296/29552310-4de827f2-8749-11e7-9808-285a4c850ce0.jpg)

6. Press `i` to enter insert mode. 
![3](https://user-images.githubusercontent.com/2340296/29552315-54300f12-8749-11e7-96e1-b93dd3783b29.jpg)

7. Now, find the input is not English, so delete the letter i and switch IME to English input mode.
8. Press `i`, enter the insert mode.
9. Press `enter`, input a new line to div tag.
![4](https://user-images.githubusercontent.com/2340296/29552324-5c4c3cb6-8749-11e7-857b-6230e2fb70a6.jpg)

10. Press `a` to insert a letter `a` to the tag.

Excepted: 
```
<div>
    a
</div>
```

Actual: 
```
<diva></div>
```
![5](https://user-images.githubusercontent.com/2340296/29552334-66e3ae02-8749-11e7-8f51-52587d159a11.jpg)

**Comment by oknixus** [comment] 2017-08-31 08:08
@yubaoquan 你有没有遇到过，切换模式（switch normal to insert）后的第一次输入，会发生光标漂移，eg：本来是要在当前行输入的，但是按键后发现，输入的内容到了之前光标待过的某一个位置。
我尝试禁用除vim-mode-plus以外的所有Community Packages，结果还是这样。
也禁用了vim-mode-plus，尝试使用vim-mode，还是会出现这个问题。
然后我下载了Atom 1.20.0，在使用中，还是存在这样的问题；
现在我重新下载了Atom 1.18.0，不知道会不会依然存在这个问题；
如果Atom 1.18.0不再出现此问题，那就说明，这个问题是Atom ^1.19.0，本身造成的，是Atom的bug

**Comment by oknixus** [comment] 2017-08-31 08:11
@yubaoquan 我认真看了你的描述，我想咱俩说的应该是同一个问题😂

**Comment by t9md** [comment] 2017-11-16 10:53
Duplicate of https://github.com/t9md/atom-vim-mode-plus/issues/875.

Fixed in atom-1.22.0 and later.

**Closed by t9md** 2017-11-16 10:53 UTC
