### ISSUE TITLE
Uncaught TypeError: this.peekTop(...).setTarget is not a function

### ISSUE THREAD

**Issue by Byron-TW** [t9md/atom-vim-mode-plus#185] opened 2016-03-09 11:55 UTC
[Enter steps to reproduce below:]

Unfortunately, it's rather hard to determine when it happens. But while working, it happens multiple times a day, usually just when navigating.
I know it's vague and may be hard to reproduce - if it's too much so, please feel free to close.
Also I will amend to this ticket in case I learn when exactly it happens.

**Atom Version**: 1.5.4
**System**: Mac OS X 10.11.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: this.peekTop(...).setTarget is not a function

```
At /Users/sthiel/dev/cs/atom-vim-mode-plus/lib/operation-stack.coffee:45

TypeError: this.peekTop(...).setTarget is not a function
    at OperationStack.process (/Users/sthiel/dev/cs/atom-vim-mode-plus/lib/operation-stack.coffee:57:20)
    at OperationStack.run (/Users/sthiel/dev/cs/atom-vim-mode-plus/lib/operation-stack.coffee:37:8)
    at run (/Users/sthiel/dev/cs/atom-vim-mode-plus/lib/base.coffee:13:29)
    at atom-text-editor.<anonymous> (/Users/sthiel/dev/cs/atom-vim-mode-plus/lib/base.coffee:200:65)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:44.1.0 find-and-replace:confirm (atom-text-editor.editor.mini.is-focused)
     -0:42.8.0 find-and-replace:focus-next (atom-text-editor.editor.mini.is-focused)
     -0:42.8.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:42.2.0 find-and-replace:replace-all (atom-text-editor.editor.mini.is-focused)
     -0:40.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:40.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  3x -0:40.9.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:40.1.0 core:save (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  2x -0:38.9.0 blur (atom-text-editor.editor.vim-mode-plus.is-focused.visual-mode.characterwise)
     -0:34.4.0 linter:next-error (atom-text-editor.editor.vim-mode-plus.visual-mode.characterwise.is-focused)
  2x -0:34.4.0 blur (atom-text-editor.editor.vim-mode-plus.visual-mode.characterwise.is-focused)
     -0:20.9.0 vim-mode-plus:find (atom-text-editor.editor.vim-mode-plus.visual-mode.characterwise.is-focused)
  3x -0:20.9.0 blur (atom-text-editor.editor.vim-mode-plus.visual-mode.characterwise.is-focused)
     -0:19.1.0 vim-mode-plus:find (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
     -0:18.6.0 vim-mode-plus:move-to-previous-paragraph (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
  4x -0:14.8.0 blur (atom-text-editor.editor.vim-mode-plus.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "linter-jshint"
    ],
    "excludeVcsIgnoredPaths": true,
    "packagesWithKeymapsDisabled": [
      "turbo-javascript",
      "git-blame",
      "vim-mode-plus",
      "es6-javascript",
      "emmet",
      "node-debugger"
    ],
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  },
  "editor": {
    "fontSize": 16,
    "invisibles": {},
    "scrollPastEnd": true,
    "showIndentGuide": true
  }
}
```

### Installed Packages

```coffee
# User
aligner, v0.19.1
atom-beautify, v0.28.26
atom-material-ui, v1.2.0
atom-ternjs, v0.13.2
atom-typescript, v8.3.0
autocomplete-ctags, v0.4.0
autocomplete-python, v1.7.0
autocomplete-ruby, v0.1.0
build, v0.55.0
build-cargo, v0.12.0
build-make, v0.7.0
coffee-compile, v0.21.1
css-snippets, v0.9.0
cursor-history, v0.5.9
emmet, v2.4.2
expand-region, v0.2.4
javascript-snippets, v1.2.1
language-apache, v1.4.0
language-elm, v1.3.3
language-escript, v0.1.0
language-jade, v0.6.3
language-mako, v0.6.0
language-rust, v0.4.6
linter, v1.11.3
linter-clang, v3.4.4
linter-coffeelint, v1.1.2
linter-csslint, v1.3.2
linter-docker, v0.1.2
linter-elm-make, v0.4.0
linter-eslint, v7.0.0
linter-flake8, v1.13.0
linter-golinter, v1.2.0
linter-htmlhint, v1.0.3
linter-javac, v1.8.0
linter-js-standard, v3.2.1
linter-js-yaml, v1.2.5
linter-jscs, v3.4.8
linter-jsonlint, v1.1.6
linter-jsxhint, v0.1.2
linter-lua, v1.0.1
linter-markdown, v1.5.0
linter-pylint, v1.2.0
linter-python-pep8, v0.2.0
linter-ruby, v1.2.2
linter-rust, v0.4.1
linter-sass-lint, v1.1.1
linter-scss-lint, v2.5.1
linter-shellcheck, v1.1.0
linter-tslint, v0.8.3
linter-xmllint, v1.3.4
minimap, v4.19.0
minimap-git-diff, v4.1.8
minimap-linter, v1.1.1
node_modules, vundefined
pretty-json, v0.4.1
project-manager, v2.7.6
racer, v0.18.0
react, v0.14.1
react-es6-snippets, v0.3.0
react-snippets, v0.3.0
rust-api-docs-helper, v0.5.1
snippets-jade, v0.1.1
source-preview-jade, v0.1.1
source-preview-react, v0.2.0
symbol-gen, v1.0.0
symbols-tree-view, v0.11.0
vim-mode-plus, v0.23.0
you-complete-me, v0.7.1

# Dev
No dev packages
```

**Comment by t9md** [comment] 2016-03-09 14:59
You have `use Shadow DOM` enabled? 
Check core section of settng-view by  `cmd-.`.

**Comment by Byron-TW** [comment] 2016-03-09 15:14
Yes, it is enabled. I believe you are suggesting to disable it, and so I did just to evaluate if these issues go away.
The setting's description looked like it is going to go away eventually, maybe making the shadow DOM mandatory. Does this affect `vim-mode-plus`, eventually ?
Thank you

**Comment by Byron-TW** [comment] 2016-03-09 15:15
Oh, actually it is the other way around. 
![screen shot 2016-03-09 at 4 14 44 pm](https://cloud.githubusercontent.com/assets/15169434/13639679/22bd8f1a-e612-11e5-9819-3f2fb5f88665.png)

Now I have enabled it again, as it was the case before.

**Comment by jordwalke** [comment] 2016-03-10 04:41
I actually did see this error again while pressing `n` for search-next. It's nowhere near as common as it was before, but I'll keep an eye out for a repro. (I have the correct shadow DOM setting).

**Comment by Byron-TW** [comment] 2016-03-10 09:08
@t9md I am not quite sure whether closing this issue will solve it. Do you have an explanation for why it happens ? As mentioned before, my DOM setting was correct, vim-mode-plus will not work without it anyway.

**Comment by t9md** [comment] 2016-03-11 17:41
Before explaining what happening here, I have to explain how vmp command is processed.

Most of vmp commands are processed by operationStack.

e.g-1 `ciw`
when you input `c` in normal mode. it push `Change` operation to operationStack.
since `Change` operation needs target, vmp enter `operation-pending` mode.
Next, you input `iw`, then `InnerWord` text-object is pushed to operationStack.
When `InnerWord` is pushed to operationStack, first `Change` operation is composed with `InnerWord` by calling `Change::setTarget(InnerWord)`. Here operator got target, so become executable(= `isComplete()` return `true`).
So `Change::execute()` is called and delete `inner-word` then enter `insert-mode`.

`setTarget` is Operator's methods(=`Operator::setTarget()`).
All other operation(Motion or TextObject) doesn't have `setTarget` methods.
Motion or TextObject is pushed to empty operationStack, it immediately popped and executed without entering `operator-pending` mode.

But there is some exception, motion command like `/`, `?`, `t`, `f` require extra input, these operation is not popped from operationStack until user provide required input.

What happening when  `this.peekTop(...).setTarget  is not a function` is thrown is....
Another motion is pushed to operationStack **BEFORE** first motion is popped and processed.
For example, you input `/`, `Search` operation is not popped until you input `Enter` to confirm search.
But before you enter `Enter`, another vmp command is pushed to operationStack.
Then operationStack call `Search::setTarget(SomeOperation)`  cause error, since `/` is motion , it has no `setTarget` methods.

I want to fix this error, fixing this error is very important.
But at least for me I haven't see same error, so I can't investigate interactively.
I believe this is vmp original bug, offiecial vim-mode don't have this bug.
And official vim-mode works well without enabling `shadowDOM`.
Why vmp require `shadowDOM` is simply because I'm developing vmp with `shadowDOM` enabled my Atom. I just haven't checked behavior with `shadowDOM` disabled.
I will experiment disabling `shadowDOM` and fix error.
This experiment might give hint for me to fix `this.peekTop(...).setTarget  is not a function`.

**Comment by jordwalke** [comment] 2016-03-12 00:32
I have definitely seen the error too (usually when hitting `n` to search for next). I will again be ready to report more details when I see it.

**Comment by Byron-TW** [comment] 2016-03-12 08:06
@t9md Thanks for the elaborate explanation, and for maintaining this project. It really helps me easing into Vim, and I so thankful for it !

**Comment by t9md** [comment] 2016-04-02 17:26
Change I made in vmp-v0.30.0 possibly fix this issue.
Will close this issue to **re-evaluate** issue is still happen after vmp-v0.30.0.

**Closed by t9md** 2016-04-02 17:26 UTC
Labels: bug, closed-to-re-evaluate

**Comment by t9md** [comment] 2016-04-03 03:22
After re-think, investigation, I remove **closed-to-re-evaluate** tag.
It definitely should be fixed in v0.30.0.

**Comment by admosity** [comment] 2016-04-26 02:24
I'm getting this bug in v0.37.0. Happens with the seek forward `f` after some time.

**Comment by ali** [comment] 2016-04-26 04:02
Also happening to me in v0.37.0 when I use `f` to seek ahead in a line.

**Atom Version**: 1.7.2
**System**: Mac OS X 10.11.4
**Thrown From**: [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) package, v0.37.0


### Stack Trace

Uncaught TypeError: this.peekTop(...).setTarget is not a function

```
At /Users/ali/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:53

TypeError: this.peekTop(...).setTarget is not a function
    at OperationStack.reduce (/Users/ali/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:126:18)
    at OperationStack.process (/Users/ali/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:64:8)
    at OperationStack.run (/Users/ali/.atom/packages/vim-mode-plus/lib/operation-stack.coffee:46:8)
    at Function.Base.run (/Users/ali/.atom/packages/vim-mode-plus/lib/base.coffee:262:31)
    at atom-text-editor.<anonymous> (/Users/ali/.atom/packages/vim-mode-plus/lib/base.coffee:256:74)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.2.0/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /opt/homebrew-cask/Caskroom/atom/1.2.0/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/1.2.0/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/1.2.0/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/opt/homebrew-cask/Caskroom/atom/1.2.0/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/opt/homebrew-cask/Caskroom/atom/1.2.0/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:08.5.0 vim-mode-plus:move-to-next-word (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:08.3.0 vim-mode-plus:activate-insert-mode (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:08.1.0 snippets:next-tab-stop (atom-text-editor.editor.vim-mode-plus.is-focused.insert-mode)
     -0:08.1.0 snippets:expand (atom-text-editor.editor.vim-mode-plus.is-focused.insert-mode)
     -0:08.1.0 editor:indent (atom-text-editor.editor.vim-mode-plus.is-focused.insert-mode)
     -0:07.5.0 vim-mode-plus:activate-normal-mode (atom-text-editor.editor.vim-mode-plus.is-focused.insert-mode)
     -0:07.4.0 vim-mode-plus:move-up (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:06.6.0 vim-mode-plus:move-to-last-character-of-line (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:06.0 vim-mode-plus:move-left (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:05.8.0 vim-mode-plus:activate-insert-mode (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:05.0 refactor:done (atom-text-editor.editor.vim-mode-plus.is-focused.insert-mode)
     -0:05.0 editor:newline (atom-text-editor.editor.vim-mode-plus.is-focused.insert-mode)
     -0:03.9.0 vim-mode-plus:activate-normal-mode (atom-text-editor.editor.vim-mode-plus.is-focused.insert-mode)
     -0:03.8.0 vim-mode-plus:move-up (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
  3x -0:03.5.0 vim-mode-plus:find (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode)
     -0:00.6.0 vim-mode-plus:move-right (atom-text-editor.editor.vim-mode-plus.is-focused.normal-mode.find-pending)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "symbols-view",
      "vim-mode"
    ]
  },
  "vim-mode-plus": {
    "highlightSearch": true
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.2.1
atom-ctags, v4.4.2
coffee-navigator, v0.0.16
coffee-refactor, v0.7.0
color-picker, v2.0.14
file-icons, v1.6.13
hyperclick, v0.0.35
js-hyperclick, v1.4.1
language-babel, v2.18.1
language-svg, v0.9.0
linter, v1.11.3
linter-coffeelint, v1.1.2
linter-stylint, v2.0.1
pigments, v0.19.1
redux-snippets, v0.2.2
refactor, v0.6.0
travis-ci-status, v0.18.0
vim-mode-plus, v0.37.0
vim-modeline, v0.4.0
vim-surround, v0.8.1

# Dev
No dev packages
```

**Comment by t9md** [comment] 2016-04-26 08:09
Original issue was fixed when I closed issue, bug from v0.37.0 is different cause, will fix from now.
Sorry for this degradation.

**Comment by ali** [comment] 2016-04-26 19:55
thanks for the quick fix @t9md :)

**Comment by Devagamster** [comment] 2016-07-21 07:10
I'm encountering this error again especially with bindings which are set up to be like key chords. What information can I provide to help diagnose the issue?

**Comment by t9md** [comment] 2016-07-21 08:12
- whole keymaps(`keymap.cson`)
- If you can reproduce every time, procedure how to reproduce(keymaps, setting, keystroke you typed etc.)

**Comment by Devagamster** [comment] 2016-07-23 01:05
with my key bindings, if I chord j and k I get the error

**Comment by Devagamster** [comment] 2016-07-23 01:06
I also have atom.keymaps.partialMatchTimeout = 80
in my init to make the chording less unpleasant

**Comment by t9md** [comment] 2016-07-23 01:55
@Devagamster you can reproduce it by `f j` in normal mode to invoke `command-palette:toggle` in your keymap?
If so, this is limitation I cannot fix unless upstream atom-keymap handle this correctly.
See https://github.com/t9md/atom-vim-mode-plus/issues/254 and links in comment for detail.
To avoid this error

- Don't define multi-keystroke keybinding starting with one of `f`, `F`, `/`, `?`, ``` ` ```, `'`.

**Comment by t9md** [comment] 2016-07-23 01:58
I cannot understand why `j k` chord cause this error.
As I said. Please put your keymap.cson and precise keystroke to reproduce this issue.
I won't respond no more unless you provide this information.
I also set `j k` to back to normal-mode from insert-mode [here](https://github.com/t9md/dotfiles/blob/master/atom/keymap.cson#L274)  and have no problem? What's the difference?

**Comment by Devagamster** [comment] 2016-07-23 22:05
My keymap.cson is in the edit of the original post. I have found that in normal mode, if you chord fd fs or fs they all trigger the error consistently. I dont have a binding for those keys which is why its confusing it would cause an error. It doesn't trigger the error if the keys are not chorded.

**Comment by t9md** [comment] 2016-07-24 00:19
As I wrote in https://github.com/t9md/atom-vim-mode-plus/issues/185#issuecomment-234692656 , this is limitation of atom-keymaps(I've already file PR for this but still not get feedback).
So what I can say again is DONT set keymaps prefixed with `f`.
