### ISSUE TITLE
"gq" isn't working

### ISSUE THREAD

**Issue by jrmiller82** [t9md/atom-vim-mode-plus#629] opened 2016-12-23 18:21 UTC
g motions don't appear to be working; which are pretty important for a vim-style workflow. 

For example: `gqip` would refill / hard-wrap the current paragraph. Or `Shift-v`, select several lines then `gq` would hardwrap the visual-line mode selected lines.

**Comment by t9md** [comment] 2016-12-23 18:38
Duplicate of old #187 .
I come up with idea so follow above issue if you want.

**Closed by t9md** 2016-12-23 18:38 UTC
Labels: duplicate
