### ISSUE TITLE
Incorrect cursor rendering in visual mode on blank line.

### ISSUE THREAD

**Issue by jordwalke** [t9md/atom-vim-mode-plus#154] opened 2016-02-10 09:04 UTC
Repro:
- Move cursor to blank line with no text on it (not even white space).
- Press `v`.
- While you have configured a custom line height (try 1.2)
```
  editor:
    fontSize: 11
    invisibles: {}
    lineHeight: 1.2
```

Symptom: The cursor is misaligned with the line height:
See screenshot:
![screen shot 2016-02-10 at 1 00 21 am](https://cloud.githubusercontent.com/assets/977348/12942788/300045be-cf92-11e5-9503-c1b0e28697be.png)

**Comment by t9md** [comment] 2016-02-10 15:11
@jordwalke The condition this happen is only when you change lineHeight config while you selected blank line right?
This is very minor issue, I appreciate reporting this issue itself but I feel its no problem if I won't fixed it.

@crshd I merged your patch and tried but original issue still happen.
Did you confirmed issue solved with your fix?
I'll try from now( I believe to fix this, I have to observe lineHeight change and update cursor style on this change event).

**Comment by t9md** [comment] 2016-02-10 15:21
@crshd I understand the point of your patch.
Its necessary. Thanks.

**Comment by t9md** [comment] 2016-02-10 15:36
@jordwalke No need to respond, This issue should be fixed.
Thanks for reporting.

**Closed** 2016-02-10 15:39 UTC

**Comment by crshd** [comment] 2016-02-10 16:20
Huh. My patch was working for me, even when changing the line height after loading vmp. But using an observer is the cleaner way to go about that, anyways.

**Comment by t9md** [comment] 2016-02-10 16:31
Yes your patch worked, with exception when you select blankline with `v` then change editor.lineHeight to different value then return original editor by clicking tab of that editor. Still blank line was selected but highlight didn't reflect new lineHeight value since there is no timing to cursorStyle refresh is called.
