### ISSUE TITLE
f and t commands are too slow

### ISSUE THREAD

**Issue by ugoa** [t9md/atom-vim-mode-plus#435] opened 2016-10-17 09:20 UTC
When using `f` or `t` command to jump to a certain place in the line, it takes a notable amount of time to get there comparing to other commands, which can be a bit annoying.

Hope there could be a faster solution for this. Thanks.

- Atom version info(`1.11.1`)
- vim-mode-plus version (`0.60.0`)

**Comment by t9md** [comment] 2016-10-17 09:38
Yes, I know this frustrating. I once also noticed this slowness and tried to fix that.
My investigation is here

- when f or t is repeated it isnt not slow.
- initial f and t is slow and shoud be improved
- why slow is it read user imput via mini-hidden-editor
- showing and change focus to mini-editor take certain amount of time
- so what worth trying is acheve f and t without using mini-editor
- read user input is also achievable by through keymap by providing possible char as keymap which keymap is activated only after f, t, F, T was typed
- currently m command take this approarch since mark char is limited
- I can make f, F work in same way as m for only alphanumeric char(not sure is this cover all possible chars?)
- and still this approach complecate codes and a bit tricky and not intuitive.

Anyway me too want to fix this kind of un-responsiveness.
I noticed other command's slow case(like count specified motion such as 3j is delayed) and some of it have solution. Will improve gradually.

**Comment by ugoa** [comment] 2016-10-18 05:06
@t9md Glad you noticed and planed to fix it. Great plugin for Atom!
And also I find the `r` command also have performance problem, appreciate it if you could also have a look.
Cheers!

**Comment by t9md** [comment] 2016-10-18 05:37
Yes `r` is same root cause.

**Comment by bronson** [comment] 2016-10-20 06:29
Very glad you started this discussion.  It's been bothering me too but not enough to say anything.  :)

Is it worth asking the Atom authors if there's a better way of reading keypresses without spinning up a hidden editor?

**Comment by t9md** [comment] 2016-10-25 03:37
Merged to master.

Affected operation

- `f`, `F`, `t`, `T`, `r`
- Surround family operation
- JoinByInput family opeation
- InsertRegister `ctrl-r "` in `insert-mode`

Not perfectly fast like pure-Vim, but much much better than before.

**Comment by t9md** [comment] 2016-10-25 03:57
Reopened since I want to continue investigation why-so-slow-in-current-mini-editor-approach before releasing faster input version with different approach.

**Comment by t9md** [comment] 2016-10-25 09:07
Investigation done, what I found is on https://github.com/t9md/atom-vim-mode-plus/pull/448#issuecomment-255979186.

**Closed by t9md** 2016-10-25 09:07 UTC
Labels: architecture-improvement, enhancement
